//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopManagement.ModelTemp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonHang
    {
        public string MsNs { get; set; }
        public string MsSach { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual NhaSach NhaSach { get; set; }
    }
}
